application: upteer
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"
- name: pycrypto
  version: "2.3"

handlers:
######################################################################
##                  API
## "authparams" means
##   am: authentication method: "utid" (other methods may be added later)
##   at: authentication token (from local or supported external source)
##   an: authentication name (email if native auth, whatever otherwise)
##
## Queries may return a base64 cursor value as the last element.
## Optional parameters are listed in parentheses
##
######################################################################

######################################################################
##        Site authentication 

## Get build version string
## GET params: none
- url: /buildverstr.*
  script: src.py.login.app

## Get an access token from native credentials
## POST params: user, pass 
- url: /login.*
  script: src.py.login.app

## Create a new native account
## POST params: email, password
- url: /newacct.*
  script: src.py.login.app

## Read native credentials and redirect back
## POST params: emailin, passin (,returnto)
- url: /redirlogin.*
  script: src.py.login.app

## Email forgotten native account password
## POST params: email
- url: /mailcred.*
  script: src.py.login.app

## Change native account password
## POST params: password, authparams
- url: /chgpwd.*
  script: src.py.login.app


######################################################################
##        Profile access

## Retrieve profile by email address
## GET params: authparams
- url: /myprofile.*
  script: src.py.profile.app

## Retrieve profile by ID
## GET params: profid, authparams
- url: /profbyid.*
  script: src.py.profile.app

## Save a new or modified profile
## POST params: profile data, authparams
- url: /saveprof.*
  script: src.py.profile.app

## Upload a profile pic
## POST params: picfilein, _id, authparams
##   _id: The PenName instance id
- url: /profpicupload.*
  script: src.py.profile.app

## Retrieve a profile pic
## GET params: profileid
- url: /profpic.*
  script: src.py.profile.app


######################################################################
##        Organization access

## Retrieve org by ID
## GET params: orgid, authparams
- url: /orgbyid
  script: src.py.organization.app

## Save a new or modified organization
## POST params: org data, authparams
- url: /orgsave.*
  script: src.py.organization.app

## Request association to an organization
## POST params: orgid, profid, authparams
- url: /orgassoc.*
  script: src.py.organization.app

## Retrieve a few organizations with the specified name prefix
## GET params: pre, authparams
- url: /orgnames.*
  script: src.py.organization.app


######################################################################
##        Opportunity access

## Retrieve opp by ID
## GET params: oppid, authparams
- url: /oppbyid
  script: src.py.opportunity.app

## Save a new or modified opportunity
## POST params: opp data, authparams
- url: /oppsave.*
  script: src.py.opportunity.app


######################################################################
##        Match access

## Fetch the top keywords for use in matching
## GET params: search ("profile" or "opportunity"), authparams
- url: /topkeys.*
  script: src.py.match.app

## Fetch match nodes for the specified skills
## GET params: skills (CSV), authparams
- url: /match.*
  script: src.py.match.app


######################################################################
# General endpoints

## Trap anything ending with a slash and send it to index.html since
## there is no default processing to figure that out otherwise.
- url: (.*)/
  static_files: docroot/index.html
  upload: docroot

## Catchall is to look in docroot.
- url: /
  static_dir: docroot

